// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://raxegrpeaoftjunvlqjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJheGVncnBlYW9mdGp1bnZscWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjA5ODcsImV4cCI6MjA2NDMzNjk4N30.y9XqKLb7VCj8JhdKIrRUWEfnC8qXtprEK9xNXydQp5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);